### ISSUE TITLE
Optional argument 'version' causes failure if absent

### ISSUE THREAD

**Issue by sterlingbaldwin** [ESGF/output_viewer#5]
The constructor of the OutputIndex class [takes an optional](https://github.com/ESGF/output_viewer/blob/master/output_viewer/index.py#L6) argument 'version.' If that argument is missing, and the resulting json file is uploaded, it causes the upload process to fail. This behavior stems from the DiagnosticViewerClient [assuming the variable is present](https://github.com/ESGF/output_viewer/blob/master/output_viewer/diagsviewer.py#L36).

**Comment by chaosphere2112** [comment]
@sterlingbaldwin the "version" argument is the dataset's title; I'll add a default value based on the current timestamp, but due to compatibility reasons I guess the name's going to have to stick. I'll file an issue for 2.0 to fix that name.

**Comment by chaosphere2112** [comment]
Created #8 to address the semantics issue, new automatic version is in master.
